#############################################################################
# Makefile for building: BeerWallet
# Generated by qmake (3.1) (Qt 5.15.0)
# Project:  BeerWallet.pro
# Template: app
# Command: /opt/mxe/usr/i686-w64-mingw32.static/qt5/bin/qmake -o Makefile BeerWallet.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = /opt/mxe/usr/i686-w64-mingw32.static/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/mxe/usr/i686-w64-mingw32.static/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/mxe/usr/i686-w64-mingw32.static/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
IDC           = idc
IDL           = midl
ZIP           = 
DEF_FILE      = 
RES_FILE      = 
SED           = sed
MOVE          = mv -f
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: BeerWallet.pro /opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/win32-g++/qmake.conf /opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/spec_pre.prf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/qdevice.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/device_config.prf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/sanitize.conf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/gcc-base.conf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/g++-base.conf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/angle.conf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/win32/windows_vulkan_sdk.prf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/windows-vulkan.conf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/g++-win32.conf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/windows-desktop.conf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/qconfig.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axbase.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axbase_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axcontainer.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axcontainer_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axserver.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axserver_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_charts.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_help.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_location.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick3d.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick3d_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick3drender.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick3dutils.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_repparser.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_script.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_scxml.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_svg.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_webview.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_winextras.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_winextras_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_assimpsceneimport.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_defaultgeometryloader.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_dsengine.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_gltfgeometryloader.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_gltfsceneexport.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_gltfsceneimport.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_openglrenderer.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qdirect2d.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qgif.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qicns.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qico.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qjp2.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qjpeg.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qminimal.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_messages.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_preview.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmng.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qoffscreen.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlite.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlmysql.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlodbc.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlpsql.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqltds.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsvg.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsvgicon.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtaudio_windows.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtexttospeech_sapi.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtga.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtiff.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtpassthrucanbus.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtpeakcanbus.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtposition_serialnmea.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtsysteccanbus.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qttinycanbus.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtvectorcanbus.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtvirtualcanbus.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtvirtualkeyboard_hangul.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtvirtualkeyboard_openwnn.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtvirtualkeyboard_pinyin.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtvirtualkeyboard_tcime.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtvirtualkeyboard_thai.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwbmp.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwebp.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwindows.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwindowsvistastyle.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qxdgdesktopportal.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_scene2d.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_sdl2gamepad.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_windowsprintersupport.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_xinputgamepad.pri \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qt_functions.prf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qt_config.prf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/win32-g++/qmake.conf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/toolchain.prf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/default_pre.prf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/win32/default_pre.prf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/resolve_config.prf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/exclusive_builds_post.prf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/default_post.prf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/precompile_header.prf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/warn_on.prf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qt.prf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/gc_binaries.prf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/resources_functions.prf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/resources.prf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/moc.prf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/win32/opengl.prf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qmake_use.prf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/file_copies.prf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/win32/windows.prf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/testcase_targets.prf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/exceptions.prf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/yacc.prf \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/lex.prf \
		BeerWallet.pro \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/platforms/qwindows.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qgif.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qicns.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qico.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qjp2.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qjpeg.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qmng.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qtga.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qtiff.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qwbmp.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qwebp.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_debugger.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_inspector.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_local.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_messages.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_native.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_nativedebugger.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_preview.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_profiler.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_quickprofiler.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_server.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_tcp.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/bearer/qgenericbearer.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/lib/Qt5Quick.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/lib/Qt5Gui.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/lib/Qt5QmlModels.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/lib/Qt5Qml.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/lib/Qt5Network.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/lib/Qt5Core.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/qml/QtQuick.2/qtquick2plugin.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/qml/QtQuick/Controls.2/qtquickcontrols2plugin.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/qml/QtQuick/Templates.2/qtquicktemplates2plugin.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/qml/QtQuick/Window.2/windowplugin.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/qml/QtQuick/Layouts/qquicklayoutsplugin.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/qml/QtQuick3D/qquick3dplugin.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/qml/QtQuick3D/Materials/qtquick3dmaterialplugin.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/qml/QtQuick/Controls.2/Material/qtquickcontrols2materialstyleplugin.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/qml/QtQuick/Controls.2/Imagine/qtquickcontrols2imaginestyleplugin.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/qml/QtGraphicalEffects/qtgraphicaleffectsplugin.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/qml/QtGraphicalEffects/private/qtgraphicaleffectsprivate.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/qml/QtQuick/Controls.2/Fusion/qtquickcontrols2fusionstyleplugin.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/qml/QtQuick/Controls.2/Universal/qtquickcontrols2universalstyleplugin.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/lib/qtmain.prl \
		/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/build_pass.prf \
		qml.qrc \
		qml3d.qrc
	$(QMAKE) -o Makefile BeerWallet.pro
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/spec_pre.prf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/qdevice.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/device_config.prf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/sanitize.conf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/gcc-base.conf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/g++-base.conf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/angle.conf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/win32/windows_vulkan_sdk.prf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/windows-vulkan.conf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/g++-win32.conf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/common/windows-desktop.conf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/qconfig.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3danimation.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3danimation_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dextras.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3drender.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axbase.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axbase_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axcontainer.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axcontainer_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axserver.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_axserver_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_bodymovin_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_charts.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_charts_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_core.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_core_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_datavisualization.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_dbus.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gamepad.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gamepad_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gui.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_help.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_help_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_location.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_location_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_network.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_network_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_networkauth.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_networkauth_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_nfc.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_opengl.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_positioning.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_positioningquick.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_purchasing.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_purchasing_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qml.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick3d.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick3d_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick3drender.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick3drender_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick3dutils.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_remoteobjects.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_repparser.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_repparser_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_script.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_script_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_scxml.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sensors.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_serialbus.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_serialport.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sql.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_svg.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_testlib.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_texttospeech.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_uitools.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_websockets.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_webview.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_webview_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_widgets.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_winextras.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_winextras_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xml.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_lib_zlib_private.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_assimpsceneimport.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_defaultgeometryloader.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_dsengine.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_gltfgeometryloader.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_gltfsceneexport.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_gltfsceneimport.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_openglrenderer.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qdirect2d.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qgenericbearer.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qgif.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qicns.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qico.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qjp2.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qjpeg.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qminimal.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_local.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_messages.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_native.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_preview.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_server.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qmng.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qoffscreen.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlite.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlmysql.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlodbc.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqlpsql.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsqltds.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsvg.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qsvgicon.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtaudio_windows.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtexttospeech_sapi.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtga.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtiff.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtpassthrucanbus.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtpeakcanbus.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtposition_serialnmea.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtsysteccanbus.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qttinycanbus.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtvectorcanbus.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtvirtualcanbus.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtvirtualkeyboard_hangul.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtvirtualkeyboard_openwnn.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtvirtualkeyboard_pinyin.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtvirtualkeyboard_tcime.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtvirtualkeyboard_thai.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwbmp.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwebp.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwindows.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qwindowsvistastyle.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_qxdgdesktopportal.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_scene2d.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_sdl2gamepad.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_windowsprintersupport.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/modules/qt_plugin_xinputgamepad.pri:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qt_functions.prf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qt_config.prf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/win32-g++/qmake.conf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/exclusive_builds.prf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/toolchain.prf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/default_pre.prf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/win32/default_pre.prf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/resolve_config.prf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/exclusive_builds_post.prf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/default_post.prf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/precompile_header.prf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/warn_on.prf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qt.prf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/gc_binaries.prf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/resources_functions.prf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/resources.prf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/moc.prf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/win32/opengl.prf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/qmake_use.prf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/file_copies.prf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/win32/windows.prf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/testcase_targets.prf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/exceptions.prf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/yacc.prf:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/lex.prf:
BeerWallet.pro:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/platforms/qwindows.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qgif.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qicns.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qico.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qjp2.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qjpeg.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qmng.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qtga.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qtiff.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qwbmp.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/imageformats/qwebp.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_debugger.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_inspector.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_local.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_messages.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_native.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_nativedebugger.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_preview.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_profiler.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_quickprofiler.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_server.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/qmltooling/qmldbg_tcp.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/plugins/bearer/qgenericbearer.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/lib/Qt5Quick.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/lib/Qt5Gui.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/lib/Qt5QmlModels.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/lib/Qt5Qml.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/lib/Qt5Network.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/lib/Qt5Core.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/qml/QtQuick.2/qtquick2plugin.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/qml/QtQuick/Controls.2/qtquickcontrols2plugin.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/qml/QtQuick/Templates.2/qtquicktemplates2plugin.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/qml/QtQuick/Window.2/windowplugin.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/qml/QtQuick/Layouts/qquicklayoutsplugin.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/qml/QtQuick3D/qquick3dplugin.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/qml/QtQuick3D/Materials/qtquick3dmaterialplugin.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/qml/QtQuick/Controls.2/Material/qtquickcontrols2materialstyleplugin.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/qml/QtQuick/Controls.2/Imagine/qtquickcontrols2imaginestyleplugin.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/qml/QtGraphicalEffects/qtgraphicaleffectsplugin.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/qml/QtGraphicalEffects/private/qtgraphicaleffectsprivate.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/qml/QtQuick/Controls.2/Fusion/qtquickcontrols2fusionstyleplugin.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/qml/QtQuick/Controls.2/Universal/qtquickcontrols2universalstyleplugin.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/lib/qtmain.prl:
/opt/mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/features/build_pass.prf:
qml.qrc:
qml3d.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile BeerWallet.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) /home/antoine/Documents/QtProject/BeerWallet/beerwallet_plugin_import.cpp /home/antoine/Documents/QtProject/BeerWallet/beerwallet_qml_plugin_import.cpp .qmake.stash

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
